version: "{build}"
clone_folder: "C:\\WORK"

environment:
  global:
    CABAL: "cabal --store-dir=C:\\SR --http-transport=plain-http"
    CABAL_VERSION: "2.4.1.0"
    HC: "ghc"
    TEST: "--enable-tests"
    NOTEST: "--disable-tests"
    BENCH: "--enable-benchmarks"
    NOBENCH: "--enable-benchmarks"
  matrix:
    # We don't get many build bots with Appveyor so we only include the
    # latest for each major version.
    - GHC_VERSION: "8.6.4"
    #- GHC_VERSION: "8.6.3"
    #- GHC_VERSION: "8.6.2"
    #- GHC_VERSION: "8.6.1"
    - GHC_VERSION: "8.4.4"
    #- GHC_VERSION: "8.4.3"
    #- GHC_VERSION: "8.4.2"
    #- GHC_VERSION: "8.4.1"
    - GHC_VERSION: "8.2.2"
    - GHC_VERSION: "8.0.2"
    #- GHC_VERSION: "8.0.1"

cache:
 - "C:\\SR"

install:
 - "choco install -y ghc --version %GHC_VERSION%"
 - "choco install -y cabal --version %CABAL_VERSION%"
 - "refreshenv"
 - "%CABAL% --version"
 - "%HC% --version"
 - "%CABAL% new-update"
 - "%CABAL% new-build -w %HC% %TEST% %BENCH% --dep -j2 all"
 - "%CABAL% new-build -w %HC% %NOTEST% %NOBENCH% --dep -j2 all"

build: off

# test_script mostly transcribed from .travis.yml
test_script:
 # show project file
 - "cat cabal.project || true"
 
 # this builds all libraries and executables (without tests/benchmarks)
 - "%CABAL% new-build --disable-tests --disable-benchmarks all"
 
 # build & run tests, build benchmarks
 - "%CABAL% new-build -w %HC% %TEST% %BENCH% all"
 - "%CABAL% new-test -w %HC% %TEST% %BENCH% all"
 
 # haddock
 - "%CABAL% new-haddock -w %HC% %TEST% %BENCH% all"
